### ISSUE TITLE
running on linux over wine

### ISSUE THREAD

**Issue by banjochose** [nicehash/NiceHashBot#16]
root@localhost:~/Downloads# wine NiceHashBot.exe 
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
[12/11/2016 03:30:13] INFO: Initializating API Wrapper with ID=MYID and Key=KEY
[12/11/2016 03:30:13] INFO: This program is compatible with API version 1.2.6
[12/11/2016 03:30:15] ERROR: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
[12/11/2016 03:30:15] ERROR: Failed to get API Version.

**Comment by dedxi** [comment]
I haven't tested everything, but it seems to work for me (ArchLinux x86_64, Wine 2.0-rc3) when installed via [PlayonLinux](https://www.playonlinux.com/en/) with the following steps:

1) Click install button
2) "Install a non-listed program" (lower left of the window)
3) "Next", "Next", "Install a program in a new virtual drive", Type in a name like "NiceHashBot" and "Next"
4) Select "Install some libraries" and click "Next"
5) "Next" (32 bit install is probably best)
6) Scroll down to "POL_install_dotnet_20", select it, click "Next", wait a few seconds
7) Now the virtual drive is created, so copy the nicehasbot files to ~/.PlayOnLinux/wineprefix/NiceHashBot/drive_c/Program Files/ (or whatever you named the virtual drive)
8) It asks for an install file, but you can select any windows program, try selecting the NiceHashBot.exe from the folder you just copied it to above, it should run if everything worked
8) Click Next and try out the program for a bit, or just close it to move on
9) You should see the NiceHashBot.exe file in the list, select it an click Next to make a shortcut, name it, Next again
10) Hit Cancel and you're done.

You should be able to launch it from POL now.

**Comment by Fornax96** [comment]
Is there no way to build it with Mono? Seems a bit devious to install Wine just to run an open source app.
