### ISSUE TITLE
stuck in price decrease loop?

### ISSUE THREAD

**Issue by Deekor** [nicehash/NiceHashBot#18]
I've been without hashing speed (0.000) for about 30 minutes now and all the bot has done is decrease my price, how does that make sense?

My max price is 0.606 and my minimum is 0.5 and speed limit is 1.0

I'm seeing several other orders with hashrate in that price range.

![capture](https://cloud.githubusercontent.com/assets/1904267/24033259/ad7e058e-0ab1-11e7-9703-2f8dad2a8b4e.PNG)

![capture2](https://cloud.githubusercontent.com/assets/1904267/24033290/cf8068f2-0ab1-11e7-8b83-2dc3efa0cb64.PNG)

**Comment by Shymmy** [comment]
I have this same problem on CryptoNight and Equihash algorithms. Anyone know's how to fix this?

**Comment by JoshCason** [comment]
Had the same problem with Equihash and SHA256.

**Comment by Grimm2017** [comment]
On Equihash the bot seems to always jump to my max price and if I drop the max price it only decreases by 0.01 every ten minutes.  Dagger hashing seems to work better for some reason.
