### ISSUE TITLE
RPC flood

### ISSUE THREAD

**Issue by kenshirothefist** [nicehash/NiceHashBot#19]
User may get a warning "RPC flood detected" which means, that it makes to many API calls and triggers service's limits.

**Comment by shtse8** [comment]
What is the rate limit?

**Comment by shtse8** [comment]
@kenshirothefist Hello., I would like to know  the rate limit to prevent the "RPC flood detected"

**Comment by ITmasterFA** [comment]
Try not to use multiple orders at once. For this, use separate nicehash accounts/API Key on separate copies of the bot.   You can try the mod as well
http://nicehashbotmod.uk.to

**Comment by shtse8** [comment]
It is too troublesome to manage too many accounts,
