### ISSUE TITLE
Running with Mono fails because of AllocConsole

### ISSUE THREAD

**Issue by gdhaworth** [nicehash/NiceHashBot#2]
I wanted to run this on Linux, so I tried building it through MonoDevelop. It seems to fit nicely except for the call to `AllocConsole()` in `kernel32.dll`. I [commented out the call](https://github.com/nicehash/NiceHashBot/blob/master/src/NiceHashBotLib/LibConsole.cs#L23) in `LibConsole.OpenConsole()` and it started up just fine. I don't have any CSharp/.NET/Mono experience but if there is a .NET equivalent of that call it may work in Mono.

I know you're not supporting Mono as a runtime but it seems to work just fine for me. It would be a shame to miss out on the Linux and Mac userbase because of something so small! I'm happy to do some testing for you on Linux or Mac.

P.S. I tried running it with WINE which did not work on my system. It may work for most WINE installations but I do not have the certificate root trust store set up correctly for this in WINE on my system.

**Comment by nicehashdev** [comment]
Console offers no extra functionality but to print out what is happening behind the hood. Unfortunately, there is no simple way to make this platform independant, becuase Linux does not provide same oe similar console methods - such as ability to attach console window to a process.

**Comment by gdhaworth** [comment]
That's true, but is it necessary on all platforms? In the case of Linux I would expect most users know to launch the program from the terminal when they want to see console output from the application (which works just fine, it even colored the output based on severity). OS X would be a little different.

This is all up to you of course :smiley: but I was just thinking there may be a .NET equivalent of the call that allows you to make a minimal change to allow out-of-the-box support for other platforms. At least on linux it would be okay if this equivalent call was a no-op.

**Comment by bitbandi** [comment]
use #if !MONO precondition

**Comment by nicehashdev** [comment]
Will use bitbandi's suggestion.
