### ISSUE TITLE
WARNING: Remote message: 'Bad pool.' for request method 'orders.create'

### ISSUE THREAD

**Issue by aldanciprian** [nicehash/NiceHashBot#20]
The exact pool informations that I used on the web work, bot on the nicehash bot not.

stratum+tcp://eth.suprnova.cc    
5000
and as my login and password I have this format
loginname.workername
workerpassword

Every order I create I get this error. I am unable to use this software.

Please help.
v1.0.3.3 is the software version.
I am on WINDOWS 10.

**Comment by trtnwg** [comment]
Late response. 

Enter eth.suprnova.cc as the pool address, without the stratum part.
Everything else looks fine.
