### ISSUE TITLE
Does the settings dialog need to be opened every time the app is launched?

### ISSUE THREAD

**Issue by Grimm2017** [nicehash/NiceHashBot#22]
It's kind of annoying since those settings are rarely changed.

**Comment by ITmasterFA** [comment]
I need to fix that issue for settings box. Anyone guide me how to contribute code edit on github?

**Comment by discipuloosho** [comment]
https://github.com/discipuloosho/NiceHashBot/commit/5e5f8c85f5df918ea82b85bfd037ee74d1cec788
