### ISSUE TITLE
Nicehash bot 1.0.3.3 can not increace price

### ISSUE THREAD

**Issue by himawanwi** [nicehash/NiceHashBot#27]
why Nicehash bot 1.0.3.3 can not increace price (just only decrease price and reffil order only) for Sha256?
this case happen after few days nicehash bot error like this previous issue "Unhandled Exception".
and the bot always get 'Warning RPC flood detected'
Please help

**Comment by shtse8** [comment]
https://github.com/nicehash/NiceHashBot/issues/19

**Comment by lxp365** [comment]
I have also encountered the same problem

**Comment by lxp365** [comment]
I have also encountered the same problem

**Comment by ITmasterFA** [comment]
http://nicehashbotmod.uk.to

On 19 Sep 2017 15:17, lxp365 <notifications@github.com> wrote:

I have also encountered the same problem

**Comment by tomaskac** [comment]
Hi All

did anyone get app from @ITmasterFA  ? does it work?

**Comment by shtse8** [comment]
any updates?

**Comment by a709090319** [comment]
@ITmasterFA   i want buy nicehashbotmod.how to contact you

**Comment by a709090319** [comment]
http://nicehashbotmod.uk.  it's not work .   :rtemote message "access denied."  for request metod "orders.create "

**Comment by Poolmin** [comment]
If you would use a bot 100% free consider https;//poolmin.com
