### ISSUE TITLE
NiceHashBot v1.0.3.3   There are many problems

### ISSUE THREAD

**Issue by lxp365** [nicehash/NiceHashBot#29]
NiceHashBot v1.0.3.3

There are many problems
First, change the price is very slow, I created the order after a long time, the order price has remained "0.0010" for a long time. The hash always been "0" and it does not seem to automatically change the price, which leads me to have been unable to get hashing power

Second, I manually set the order to a suitable price, but when someone else's order exceeds my price, the NiceHashBot raised the price very slowly, and even kept the original price unchanged until my order dies for a long time , After my test, this happens in CryptoNight and Equihash algorithms

Third, this happens at sha256, no matter how i set it up, the order price has been continuously lowered even if the order price is lower than all until the order dies. The The The The

I am a big customer of NICEHASH, I need NiceHashBot to manage my large number of orders, hope you can understand, and give me a reply, thank you

**Comment by ITmasterFA** [comment]
Good news is near...

On 19 Sep 2017 15:51, lxp365 <notifications@github.com> wrote:

NiceHashBot v1.0.3.3

There are many problems
First, change the price is very slow, I created the order after a long time, the order price has remained "0.0010" for a long time. The hash always been "0" and it does not seem to automatically change the price, which leads me to have been unable to get hashing power

Second, I manually set the order to a suitable price, but when someone else's order exceeds my price, the NiceHashBot raised the price very slowly, and even kept the original price unchanged until my order dies for a long time , After my test, this happens in CryptoNight and Equihash algorithms

Third, this happens at sha256, no matter how i set it up, the order price has been continuously lowered even if the order price is lower than all until the order dies. The The The The

I am a big customer of NICEHASH, I need NiceHashBot to manage my large number of orders, hope you can understand, and give me a reply, thank you

**Comment by lxp365** [comment]
what do you mean
Will there be a new version to solve these problem

**Comment by ITmasterFA** [comment]
http://nicehashbotmod.uk.to

On 19 Sep 2017 15:51, lxp365 <notifications@github.com> wrote:

NiceHashBot v1.0.3.3

There are many problems
First, change the price is very slow, I created the order after a long time, the order price has remained "0.0010" for a long time. The hash always been "0" and it does not seem to automatically change the price, which leads me to have been unable to get hashing power

Second, I manually set the order to a suitable price, but when someone else's order exceeds my price, the NiceHashBot raised the price very slowly, and even kept the original price unchanged until my order dies for a long time , After my test, this happens in CryptoNight and Equihash algorithms

Third, this happens at sha256, no matter how i set it up, the order price has been continuously lowered even if the order price is lower than all until the order dies. The The The The

I am a big customer of NICEHASH, I need NiceHashBot to manage my large number of orders, hope you can understand, and give me a reply, thank you

**Comment by lxp365** [comment]
itx-_@live.com，Is this your email? I have sent an email and I'm not sure if you have received my mail
If you receive my mail, please reply to me, thank you

**Comment by ITmasterFA** [comment]
In its way

**Comment by lxp365** [comment]
I sent a message to "itx-_@live.com", did you get it?
My email is 157311111@qq.com
Please reply to me and help me get the MODKEY

**Comment by lxp365** [comment]
I have sent an e-mail to your mailbox and paid for the BTC you need
Please check and reply to me

**Comment by UltimateNewbie** [comment]
Would love to see an update/fix for this.
Aside from the SHA256, great bit. Good job guys :+1:

**Comment by Poolmin** [comment]
If you would use a bot 100% free with realtime parameter changing and simultaneous execution consider [https://poolmin.com](https://poolmin.com)
