### ISSUE TITLE
Order price goes straight to maximal.

### ISSUE THREAD

**Issue by mattanah** [nicehash/NiceHashBot#30]
With very low hash rates with plenty of room to drop the price and still fill the order it goes straight to my maximal price with no "bidding up" to see if it could fill it at a lower price.  Once the order is filled it never lowers the price even with plenty of room to do so.

**Comment by ITmasterFA** [comment]
Good news is near.

On 23 Sep 2017 7:17 pm, mattanah <notifications@github.com> wrote:

With very low hash rates with plenty of room to drop the price and still fill the order it goes straight to my maximal price with no "bidding up" to see if it could fill it at a lower price. Once the order is filled it never lowers the price even with plenty of room to do so.

**Comment by mattanah** [comment]
"Good news is near."

What?  Is the Lord our Savior about to return?    I'm going to assume you are a troll.

**Comment by ITmasterFA** [comment]
visit  http://nicehashbotmod.uk.to

On 24 Sep 2017 16:10, mattanah <notifications@github.com> wrote:

"Good news is near."

What? Is the Lord our Savior about to return? I'm going to assume you are a troll.
