### ISSUE TITLE
1.0.3.3 Username not transmitted correctly to API

### ISSUE THREAD

**Issue by damole1984** [nicehash/NiceHashBot#31]
I am using NiceHash Bot on a Windows 10 with german keyboard layout. The username in the pool is "WalletAdress+1024" but the submitted username in the NiceHash API is "WalletAdress 1024" with a space in it.
This results in all the funds being lost.
Can you reproduce the issue and provide a fix?

**Comment by amacar** [comment]
Hi.
As I checked the code, parameters are not encoded, that is why + is decoded as "space".
I didn't test this, but you can try escaping '+' sign with '%2B'.
So instead of "WalletAddress+1024" you put in "WalletAddress%2B1234".
