### ISSUE TITLE
New account appId maximum value 1000000.

### ISSUE THREAD

**Issue by cheerymagicsoftware** [nicehash/NiceHashBot#34]
Hello.
I've just registered new nisehash account and downloaded nisehashbot application. 
My appId 102****, but in app settings appId max value is 1000000 and app throw exception -> "System.ArgumentOutOfRangeException: Value "102****" is not valid for "Value". "Value" must be in the range from 'Minimum' to 'Maximum'."
It looks like https://github.com/nicehash/NiceHashBot/pull/33
Thanks.

**Comment by ITmasterFA** [comment]
Hi,
You may install from http://nicehashbotmod.uk.to

**Comment by ITmasterFA** [comment]
I'm not gonna drain your account. Trying to do some part time work here.

**Comment by JM-Punisher** [comment]
please understand that i'm new to nicehash, and that you have to be careful there are scams everywhere

**Comment by ITmasterFA** [comment]
Totally up to you. If you need to try and pay later on youre welcome

**Comment by twocs** [comment]
You can make a minor change to increase the hard coded maximum value of "1,000,000" and recompile. That's all that #33 does.
