### ISSUE TITLE
Warning: Service API has changed. This program may not work fully correctly.

### ISSUE THREAD

**Issue by maupet** [nicehash/NiceHashBot#35]
I am getting two warnings and one error as I launch:

Warning: Service API has changed. This program may not work fully correctly.
Warning: Remote Message: 'Incorrect key.' for request method 'balance'.
Error: Unable to get balance. Are ID and Key correct?

I am noticing that when I enter my API ID, it gets changed automatically to 1000000, every time.

**Comment by maupet** [comment]
It seems that the API ID field max value is 1000000, but my API ID is greater than that!

**Comment by ITmasterFA** [comment]
download from www.nicehashbotmod.uk.to

**Comment by ITmasterFA** [comment]
Download from www.nicehashbotmod.uk.to

**Comment by twocs** [comment]
This is the same as pull request #33 for this issue.

**Comment by mikeghen** [comment]
Getting the same message: 
>Warning: Service API has changed. This program may not work fully correctly.

**Comment by ITmasterFA** [comment]
You can download from here http://nicehashbotmod.uk.to

Its unofficial

**Comment by Poolmin** [comment]
[https://poolmin.com](https://poolmin.com) That's 100% free bot for mine with nicehash
