### ISSUE TITLE
refill amount should be configurable

### ISSUE THREAD

**Issue by kenshirothefist** [nicehash/NiceHashBot#4]
When using high hash rate orders it may happen that order will be depleted before bot refills it ... refill amount should be either configurable or the bot should refill such orders more frequently.

**Comment by kenshirothefist** [comment]
Since the minimum Pay per order is set to 0.01 this should also be the default refill amount.

**Comment by Grimm2017** [comment]
I would also like to see an option to disable auto refills.  Maybe also an option to manually refill at any time, if possible.
