### ISSUE TITLE
Bot goes Idle and does not check once per minute the price

### ISSUE THREAD

**Issue by leon-cgn** [nicehash/NiceHashBot#41]
Good job with the new bot! It's working (kinda) must a good tutorial to connect to the API.

When I place an order and active the bot, it checks the price once and adjusts my price. Afterwards, the bot goes into Idle and doesn't check the price any more. I expected the but to check the price once a minute (and see the output in the console). Do I need to do something to keep the bot running and check the price once a minute and adjust the price if necessary? 

Edit: I run the Bot on win10 in a virtualbox

**Comment by bl4z** [comment]
did u **turn bot On** in lower left corner .. see video 
https://storage.googleapis.com/public-prod-data/marketing%2FcreateOrder.gif

in this case bot should do his work once a minute ..

**Comment by leon-cgn** [comment]
Yes I did turn the bot on, it checks the price once and adjust the order. The the bots goes into idle mode and does not awake again.
I just gave the API "marketplace" permissions. Can that cause the bot to stop running after one iteration of price checking and adjusting?

**Comment by bl4z** [comment]
https://pasteboard.co/J3i8ZhQ.jpg

each minute bot should go from **idle** to **working** and there should be some output in console

**Comment by leon-cgn** [comment]
I got it working by creating a new API key with more permissions.
Before the bot's Api key had only "market place" permission. This was not working and the bot did not leave idle mode after first iteration.
With permissions for everything despite "user management" and "withdraw funds" the bot is working now. Once a minute it changes from "idle" to "working", checks the price and adjusts if necessary.

One questions which does not belong to this ticket: Does the 10 min time frame from the UI apply to the bot, too? Like you can change the order price just once per 10 min? 
Thanks!

**Comment by bl4z** [comment]
ill dblcheck what permissions bot needs and put in description but i assume manage orders for adjusting price and wallet for refilling .. as for adjusting price ... if lower price hash-power is available bot will try to decrease price every minute but it will be rejected by backend ... and order price will be actually preformed when backend will allow (this is once per 10 minutes)

**Comment by leon-cgn** [comment]
thanks for clarify and keep up the good work!
