### ISSUE TITLE
Numerous assembly errors.

### ISSUE THREAD

**Issue by Uberi-puzo** [nicehash/NiceHashBot#44]
Hi, it looks like the code is corrupted or not fully uploaded. I uploaded the project to VS2019 and tried to build it. And as a result, I got a lot of errors, for example:

<code>The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)</code>

<code>The type or namespace name 'JArray' could not be found (are you missing a using directive or an assembly reference?)</code>

<code>The type or namespace name 'JObject' could not be found (are you missing a using directive or an assembly reference?)</code>

<code>Could not resolve this reference. Could not locate the assembly "RestSharp, Version=106.0.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.</code>

<code>Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.</code>

Could you check the posted code and fix it? Thank you!

**Comment by bl4z** [comment]
https://www.nicehash.com/blog/post/how-to-modify-nicehash-bot

**Comment by Uberi-puzo** [comment]
Thank you, I myself understood what my mistake was. The code is fine, thanks for the bot.
