### ISSUE TITLE
Бот не корректирует цену вниз чаще одного раза в 10 минут

### ISSUE THREAD

**Issue by AlexSRS1** [nicehash/NiceHashBot#46]
res: [{"error_id":"737749fa-768c-4021-bra8-fea5f8098fc5","errors":[{"code":5061,"message":"Order price cannot be decreased yet, allowed once per 10 minutes. Seconds till available: 180"}]}]
Бот не корректирует цену вниз чаще одного раза в 10 минут, а должен 1 раз в 1 минуту

**Comment by AlexSRS1** [comment]
а должен 1 раз в минуту

**Comment by bl4z** [comment]
price up is once per minute down only once per 10 minutes
