### ISSUE TITLE
Speed limit not applied

### ISSUE THREAD

**Issue by NginUS** [nicehash/NiceHashBot#8]
See screenshot:
https://imgur.com/Nx9BinM

I have the bot set to either 0.50 or 1.00, & I still mine above 3

**Comment by nicehashdev** [comment]
Bottom limit for SHA256 is 5 TH/s, NiceHash system will not allow you to set below this limit. We will check, if this is issue with NiceHashBot displaying wrong numbers.

**Comment by nicehashdev** [comment]
NiceHashBot does not limit what you enter for speed limit, but you should follow NiceHash bottom speed limits for each algorithm on this page: https://www.nicehash.com/?p=orders&new
